# Generated by Django 5.1.7 on 2025-03-07 17:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('courier', models.CharField(db_index=True, max_length=50)),
                ('waybill_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('FAILED_DELIVERY', 'Failed Delivery'), ('RETURNED', 'Returned'), ('EXCEPTION', 'Exception'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown')], default='CREATED', max_length=20)),
                ('courier_status', models.CharField(blank=True, max_length=100)),
                ('shipment_data', models.JSONField(default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_tracked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
